# Generated by Django 3.2.7 on 2021-09-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=255)),
                ('ever_married', models.CharField(blank=True, choices=[('MARRIED', 'MARRIED'), ('SEPERATED', 'SEPERATED'), ('DIVORCED', 'DIVORCED'), ('WIDOWED', 'WIDOWED'), ('NEVER_MARRIED', 'NEVER_MARRIED')], default='NEVER_MARRIED', max_length=255)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('graduated', models.BooleanField(blank=True, default=False, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('work_experience', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('spending_score', models.PositiveIntegerField(blank=True, null=True)),
                ('family_size', models.PositiveSmallIntegerField(default=0)),
                ('anonymised_category', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=255, null=True)),
                ('segmentation', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
