# Generated by Django 3.2.7 on 2021-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=255, null=True),
        ),
    ]
