# Generated by Django 3.2.7 on 2021-09-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cars_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
