# Generated by Django 3.2.7 on 2021-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_classifieduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifieduser',
            name='ever_married',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
